### ISSUE TITLE
Cannot compile WebProtege v4.0.0 in Eclipse

### ISSUE THREAD

**Issue by titoferreira** [protegeproject/webprotege#628]
Hello,

I'm trying to compile the latest version of WebProtege (v4.0.0) in Eclipse, but the instructions available on the Web seem outdated.

I've cloned the git repository of the project and opened it in Eclipse using maven, but I still have errors.
I have tried to adapt an outdated version of such instructions I found, but  I can't compile the project in Eclipse.

Almost all my errors are of the following type, for example:

AutoValue_AnnotationComponentsCriteria cannot be resolved to a type

and one error with the following message:

Plugin execution not covered by lifecycle configuration: edu.stanford.protege:webprotege-maven-plugin:1.1.1:generatePortletFactory (execution: default, phase: generate-sources)

What am I missing to compile the new version of WebProtege in Eclipse? Is there any updated instructions available?

If you could please help i would be very grateful.

**Comment by matthewhorridge** [comment]
We use maven to build WebProtege.  If you want to look at things in Eclipse then you should first compile using maven.  This will ensure various bits of code are generated – things that you're missing now.  Use  ```mvn compile```

**Comment by titoferreira** [comment]
I've done mvn compile in the folder for where i've cloned the repository but i still have the same errors in eclipse.

Thanks in advance for your support

**Comment by johardi** [comment]
Hi @titoferreira, I had a similar issue with the Protege code base and here's how I solved it:
1. In Eclipse, go to Help -> Eclipse Marketplace... and install the `m2e-apt` plugin,
2. Make sure to enable the plugin by going to "Preferences..." and select Maven -> Annotation Processing -> Automatically configure JDT APT...
3. Clean the project and recompile everything.

Hope this helps!

**Comment by titoferreira** [comment]
Hi @johardi, thank you very much for your help.

It solved almost all my type errors that i refered above, i still have an error with JspWriter that cannot be resolved to a type.

I still have the plugin execution error that i refered above.

did you have this errors that i refer?

Thanks in advance for your support!

**Comment by johardi** [comment]
Hi @titoferreira,

Please pull the new code and do these extra steps in Eclipse:
1. Go to "Preferences... > Maven > Lifecycle Mappings" and then select "Open workspace lifecycle mappings metadata"
2. Add these lines, save, and select "Reload workspace lifecycle mappings metadata"
```
<?xml version="1.0" encoding="UTF-8"?>
<lifecycleMappingMetadata>
  <pluginExecutions>
    <pluginExecution>
      <pluginExecutionFilter>
        <groupId>edu.stanford.protege</groupId>
        <artifactId>webprotege-maven-plugin</artifactId>
        <versionRange>1.1.1</versionRange>
        <goals>
          <goal>generatePortletFactory</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <ignore />
      </action>
    </pluginExecution>
  </pluginExecutions>
</lifecycleMappingMetadata>
```
3. Rebuild the project.

This solution should fix the plugin execution error, and you shouldn't see any error markers with the new code pull in Eclipse as well.

**What's happened here?**: The issue arises because there is no m2e connector for `protege-maven-plugin` execution and the solution is to silently ignore it in Eclipse (ergo the code lines above). It doesn't alter the nature of the Maven build cycle outside Eclipse btw. You will still be able to execute `mvn clean compile` in the terminal and build WP successfully.

**Comment by titoferreira** [comment]
Hi @johardi,

Thank you, your explanation helped me to solve the plugin execution error.

I still have an error with JspWritter:

  - JspWriter cannot be resolved to a type

and this one:

 - Referenced file contains errors (http://gwtproject.org/doctype/2.8.2/gwt-module.dtd).  For more 
    information, right click on the message in the Problems View and select "Show Details..."

and the file that the error is referring to is module.gwt.xml

I'm trying to solve this two problems, but if you know how to solve i appreciate your help.

Thanks in advance for your support!
